### ISSUE TITLE
Using oe_read with specific keys and values

### ISSUE THREAD

**Issue by oprilium** [ITSLeeds/osmextract#157] opened 2020-12-31 01:07 UTC
Hello,
I have a pbf file of entire europe that downloaded from geofabrik. I would like now to read and use only key="highway" and just "motorway" and "primary". 

Importing everything takes too long. Is it possible just to import specifically the above?

Sorry if it sounds stupid... new to the topic :)

Thanks

**Comment by agila5** [comment] 2020-12-31 10:55
Hi @oprilium and thanks for your question. 

I think the following example may be useful: 

1.  Download package
``` r
remotes::install_github("ITSLeeds/osmextract")
```
2. Load package
``` r
library(osmextract)
#> Data (c) OpenStreetMap contributors, ODbL 1.0. https://www.openstreetmap.org/copyright.
#> Any product made from OpenStreetMap must cite OSM as the data source.
#> Geofabrik data are taken from https://download.geofabrik.de/
#> For usage details of bbbike data see https://download.bbbike.org/osm/
#> OpenStreetMap_fr data are taken from http://download.openstreetmap.fr/
```
3.  Define a query that will be applied during the vectortranslate process: 
``` r
my_vectortranslate_options <- c(
  "-f", "GPKG", 
  "-overwrite",
  "-lco", "GEOMETRY_NAME=geometry",
  "-where", "highway IN ('motorway', 'primary')",
  "lines"
)
```
4.  Read the data (I will use a simpler example since it takes forever to download the PBF file of Europe. It should work also if you set `place = "Europe"`)
``` r
system.time({italy <- oe_get(place = "Italy", vectortranslate_options = my_vectortranslate_options)})
#> The input place was matched with: Italy
#> File downloaded!
#> Start with the vectortranslate operations on the input file!
#> 0...10...20...30...40...50...60...70...80...90...100 - done.
#> Finished the vectortranslate operations on the input file!
#> Reading layer `lines' from data source `C:\Users\Utente\Documents\osm_data\geofabrik_italy-latest.gpkg' using driver `GPKG'
#> Simple feature collection with 117641 features and 9 fields
#> geometry type:  LINESTRING
#> dimension:      XY
#> bbox:           xmin: 6.710238 ymin: 36.71625 xmax: 18.51651 ymax: 47.05079
#> geographic CRS: WGS 84
#>    user  system elapsed 
#>  135.91   61.07  494.10
```

<sup>Created on 2020-12-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

If you have already downloaded the `.pbf` file, you may run

``` r
oe_read(place = "path_to_pbf_file", provider = "specify_the_provider", vectortranslate_options = my_vectortranslate_options)
```

**Comment by oprilium** [comment] 2021-01-01 15:05
Hello @agila5 that works!!

Thanks for your work/contribution.

**Comment by Robinlovelace** [comment] 2021-01-01 15:07
Great to hear it work @oprilium. Can you close the issue if you think it's 'fixed'? That's good practice.

**Closed** 2021-01-03 23:13 UTC

**Comment by agila5** [comment] 2021-01-04 08:48
Hi @oprilium, just one final comment. 

You may have noticed that `oe_read()` repeats the vectortranslate process every time you run the function with ad-hoc parameters (since we cannot determine if an existing GeoPackage file is identical to the result of the vectortranslate operation). The problem is that the conversion may take several minutes. In that case, my suggestion would be to save the result of `oe_read()` (with [`sf::st_write`](https://r-spatial.github.io/sf/reference/st_write.html), [`saveRDS()`](https://stat.ethz.ch/R-manual/R-devel/library/base/html/readRDS.html), [`qsave()`](https://cran.r-project.org/web/packages/qs/vignettes/vignette.html) or similar approach) and then read it again, skipping the `oe_read()` step.
